version: '3.1'

services:
  db:
    container_name: inter
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: inter-server
      POSTGRES_DB: inter
